Repository kiwiproject/dropwizard-service-utilities, pull requests merged in 2020-12, with the labels that each got.

#61 Fix Javadoc warnings in AdminConfigurator and StartupLocker
  src/main/java/org/kiwiproject/dropwizard/util/admin/AdminConfigurator.java
  src/main/java/org/kiwiproject/dropwizard/util/startup/StartupLocker.java
Labels: documentation

#62 Fix Maven convergence error with junit
  pom.xml
Labels: dependencies

#63 Fix table javadoc in MonitoredJobHealthCheck
  src/main/java/org/kiwiproject/dropwizard/util/health/MonitoredJobHealthCheck.java
Labels: bug, documentation

#64 Make ConnectorType public so it can be referenced by code using Dropwizard
  pom.xml
  src/main/java/org/kiwiproject/dropwizard/util/server/DropwizardConnectors.java
Labels: bug

#68 Ensure registerAllStandardJacksonConfigurations returns correct mapper
  src/test/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurationsTest.java
Labels: code cleanup

#69 Enhance StandardJacksonConfigurations javadocs
  src/main/java/org/kiwiproject/dropwizard/util/jackson/StandardJacksonConfigurations.java
Labels: documentation
